Repository rbtkay/INGR-Twitter, pull requests merged in 2020-05, with the labels that each got.

#2 Complete README.md
  README.md
Labels: documentation

#4 Adding a CONTRIBUTING file
  CONTRIBUTING.md
  README.md
Labels: documentation

#3 create templates
  src/.github/ISSUE_TEMPLATE/bug_report.md
  src/.github/ISSUE_TEMPLATE/feature_request.md
  src/.github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#8 move templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#16 Base CRUD of User
  README.md
  src/composer.json
  src/composer.lock
  src/config/bundles.php
  src/config/packages/dev/web_profiler.yaml
  src/config/packages/security.yaml
  src/config/packages/test/twig.yaml
  src/config/packages/test/web_profiler.yaml
  src/config/routes.yaml
  src/config/routes/dev/web_profiler.yaml
  src/src/Controller/UserController.php
  src/src/Entity/User.php
  src/src/Migrations/Version20200525150939.php
  src/src/Migrations/Version20200525154515.php
  src/src/Repository/UserRepository.php
  src/symfony.lock
Labels: enhancement

#18 Feature/code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#20 update roots of crud user
  src/src/Controller/UserController.php
Labels: enhancement

#22 Feature/homepage template
  client-app/src/components/Keywords.js
  client-app/src/components/NavigationBar.js
  client-app/src/components/Tweets.js
  client-app/src/pages/HomePage.js
  docker/docker-compose.yml
Labels: enhancement

#21 Feature/crud keywords
  src/config/routes.yaml
  src/src/Controller/KeywordController.php
  src/src/Controller/UserController.php
  src/src/Entity/Keyword.php
  src/src/Entity/User.php
  src/src/Repository/KeywordRepository.php
  src/src/Repository/UserRepository.php
Labels: enhancement

#24 Modify the crud user for front logic
  src/config/jwt/.gitignore
  src/src/Controller/UserController.php
  src/src/Repository/UserRepository.php
Labels: enhancement

#29 Adding a function to the crud user
  src/src/Controller/UserController.php
Labels: enhancement

#31 Update crud User
  src/src/Controller/UserController.php
Labels: enhancement

#33 Update the crud User
  src/src/Controller/UserController.php
  src/src/Repository/UserRepository.php
Labels: enhancement

#35 Feature/crud user
  src/src/Controller/UserController.php
  src/src/Entity/User.php
  src/src/Repository/UserRepository.php
Labels: enhancement

#40 Feature/tweets
  src/src/Entity/Tweet.php
  src/src/Entity/User.php
  src/src/Repository/TweetRepository.php
Labels: enhancement
